name: Build Docker Image

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: goesta/xmage-alpine

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker/alpine_from_release
          push: true
          tags: ${{env.IMAGE_NAME}}:latest, ${{env.IMAGE_NAME}}:${{ env.TAG }}
